### ISSUE TITLE
Problem on creating nested array

### ISSUE THREAD

**Issue by KevinGruber** [mrded/waterline-nested#1]
When the nested association is an array, i get this error:

 Could not use the provided `where` clause.  Could not filter by `translations`: Cannot filter by `translations` because it is a plural association (which wouldn't make sense).

I think the problem is in that part

49:    var output = mainModel.findOrCreate(_.clone(values), _.clone(values)).meta({fetch: true});

i guess it is because he wants to match the criteria with the array.

Hope you can solve that,

And nice, exactly what i needed... after sails omitting the nested update and create....

BR,
Kevin

**Comment by mrded** [comment]
This problem must be fixed already, but hasn't been released.

Can I ask you try git version of the package, and check is it working or not?

**Comment by mrded** [comment]
@KevinGruber can you try 0.0.4 version? The problem must be fixed there.

If you confirm that - can you please close the issue as well? Thanks.

**Comment by KevinGruber** [comment]
I will try it later.. i am at work right now but i will try it imediatly when i am home.

Thx!

BR, 
Kevin

**Comment by mrded** [comment]
You will also need `waterline` >=0.13.0-5, I forgot to specify it.

**Comment by KevinGruber** [comment]
now i get that error: 

Failed to lift app: Error: Trying to create an association on a model that doesn't have a Primary Key.

I guess it is because of a change in waterline 0.13.0-5 because i can uncomment your code and it also doesn't work...

**Comment by KevinGruber** [comment]
Ok i tried and i still get the same error:

 Could not use the provided `where` clause.  Could not filter by `translations`: Cannot filter by `translations` because it is a plural association (which wouldn't make sense).

What do you need from me to better find the problem?

BR,
Kevin

**Comment by mrded** [comment]
I'm using this lib on production, will try to get similar error..

If you can provide me models schema, and action you're trying to do. I will be able to emulate your situation.

**Comment by mrded** [comment]
@KevinGruber can you please try it again? I did a massive refactoring here https://github.com/mrded/waterline-nested/commit/59f5aae0d88bd566cf8c0f3f0b2274731b67255c and fixed race condition issues. 

It should solve your problem as well.

Open it again, if it's not solved. thanks.
